### ISSUE TITLE
Bug report: Travis badges are sometimes wrong

### ISSUE THREAD

**Issue by DilumAluthge** [bcbi/bcbi.github.io#86]
On https://bcbi.brown.edu, some of the Travis badges are wrong.

Example 1: The ModelSanitizer.jl badge currently says "build unknown." However, the ModelSanitizer.jl Travis build is currently passing. The reason for the incorrect badge is that the code in this repository assumes that all Travis builds are hosted at `travis-ci.org`. However, the Travis build for ModelSanitizer.jl is hosted at `travis-ci.com`. The correct behavior for this badge would be to show the `travis-ci.com` badge for the `master` branch of ModelSanitizer.jl.

Example 2: The SolrPlant badge currently says "build unknown". However, neither of the SolrPlant GitHub repositories have Travis enabled. The correct behavior for SolrPlant would be to not show a badge at all.

**Comment by DilumAluthge** [comment]
@ibacher Could you work on this?

**Comment by DilumAluthge** [comment]
Thanks @ibacher! The ModelSanitizer badge is now fixed. Unfortunately, the SolrPlant badge still says “build unknown.” I think we need to figure out a way to hide the SolrPlant badge entirely.

**Comment by ibacher** [comment]
@DilumAluthge: Whoops! I completely missed that part of things. This is fixed in #91.
